# Solutions to Advent of code 2023 with launcher.  

Please do not use solutions without at least trying to solve tasks on your own first.

## Usage

### Prerequirements

Software:
- OpenJDK 19 (I'm using AdoptOpenJDK, but other JDKs should work ok as well)
- Maven 3.8.3
- [Optional] JetBrains Fleet

I'm using JetBrains Fleet IDE, and there are configurations that allow Fleet to run and debug the program with Maven. 
The project layout is standard Maven layout, and IDEA, VSCode, Eclipse or any other editor that can handle Maven projects should have no problems importing it.

### Running

While in advent-of-code-2023 catalog, run following command:

[source, bash]
mvn clean install exec:java

This will build and start the program.

### Modifying

#### Adding tasks

You can add task implementations to `pl.kpro.aoc2023.tasks.impl` as classes implementing `AdventTask` interface. They will be automatically picked by the rest of after recompiling. Remember to give them distinct name and number (returned by methods declared in `AdventTask`). 

#### Task input files

You can add new input files in `resources/tasks`. Input file name must contain task name. My convention is `<taskName>-<variant>.txt`. Feel free to choose your own convention.
By default launcher expects input files to contain any UTF-8 text. Selected file is loaded into memory all at once, so avoid large files. There are no other constraints.
    
